[files]
extend-exclude = [
    "reports/references.bib", 
    "**/**.html",
    "src/climate_attitudes/builder/schema.py"
]

[default]
locale = "en-gb"

[default.extend-words]
Vitor = "Vítor"

[default.extend-identifiers]
powellModelingLeveragingIntuitive2023 = "powellModelingLeveragingIntuitive2023"
powellModellingLeveragingIntuitive2023 = "powellModelingLeveragingIntuitive2023"
center = "center"
centre = "center"
randomization = "randomization"
randomisation = "randomisation"
Randomization = "Randomization"
Randomisation = "Randomization"
