[files]
extend-exclude = [
    "reports/references.bib", 
    "**/**.html",
    "src/climate_attitudes/schema/**/**",
    "notebooks/**/**.ipynb"
]

[default]
locale = "en-gb"

[default.extend-words]
Vitor = "Vítor"

[default.extend-identifiers]
powellModelingLeveragingIntuitive2023 = "powellModelingLeveragingIntuitive2023"
powellModellingLeveragingIntuitive2023 = "powellModelingLeveragingIntuitive2023"
center = "center"
centre = "center"
color = "color"
colour = "colour"
ax = "ax"
randomization = "randomization"
randomisation = "randomization"
Randomization = "Randomization"
Randomisation = "Randomization"
