[files]
extend-exclude = [
    "reports/references.bib", 
    "**/**.html",
    "src/climate_attitudes/schema/**/**",
    "notebooks/**/**.ipynb",
    "*.excalidraw"
]

[default]
locale = "en-gb"

[default.extend-words]
Vitor = "Vítor"

[default.extend-identifiers]
lawSimulationModelingAnalysis2015 = "lawSimulationModelingAnalysis2015"
fonseca2018analisis = "fonseca2018analisis"
epskampQgraphNetworkVisualizations2012 = "epskampQgraphNetworkVisualizations2012"
mccrightPoliticizationClimateChange2011 = "mccrightPoliticizationClimateChange2011"
masonIdeologuesIssuesPolarizing2018 = "masonIdeologuesIssuesPolarizing2018"
powellModelingLeveragingIntuitive2023 = "powellModelingLeveragingIntuitive2023"
dalegeFormalizedAccountAttitudes2016 = "dalegeFormalizedAccountAttitudes2016"
dalegeFormalizedAccountAttitudes2016b = "dalegeFormalizedAccountAttitudes2016b"
epskampPersonalizedNetworkModeling2018 = "epskampPersonalizedNetworkModeling2018"
heiderAttitudesCognitiveOrganization1946 = "heiderAttitudesCognitiveOrganization1946"
cookRationalIrrationalityModeling2016 = "cookRationalIrrationalityModeling2016"
vandermaasPolarizationIndividualsHierarchical2020 = "vandermaasPolarizationIndividualsHierarchical2020"
keskinturkOrganizationPoliticalBelief2022 = "keskinturkOrganizationPoliticalBelief2022"
center = "center"
centre = "centre"
color = "color"
colour = "colour"
colors = "colors"
colours = "colours"
row_colors = "row_colors"
col_colors = "col_colors"
cbar_ax_temporal = "cbar_ax_temporal"
cbar_ax_contemp = "cbar_ax_contemp"
cbar_ax = "cbar_ax"
ax = "ax"
ax_heatmap = "ax_heatmap"
ax_row_dendrogram = "ax_row_dendrogram"
setp = "setp"
arange = "arange"
randomization = "randomization"
randomisation = "randomization"
Randomization = "Randomization"
Randomisation = "Randomization"
assume_centered = "assume_centered"
Normalize = "Normalize"

