# Timepoint at which to measure effect for all-intervention experiments 
MEASURE_TIME ?= 5

THESIS_DIR := reports/thesis
PKG_PATH := src/climate_attitudes

THESIS_DATA_DEPS := \
		$(THESIS_DIR)/results/data/dataset_metadata.json \
		$(THESIS_DIR)/results/data/model/bootstrapped_fit/ising_no_structure.npz \
		$(THESIS_DIR)/results/data/model/fit_full_sym_ising_no_structure.npz \
		$(THESIS_DIR)/results/data/model/fit_full_asym_ising_no_structure.npz \
		${CA_BUILT_ASSETS}/small_four_waves/metadata.json

THESIS_FIGURES_MODEL := \
		$(THESIS_DIR)/results/figures/methods/binarisation/distribution.pdf \
		$(THESIS_DIR)/results/figures/model/transition_probability_example.pdf \
		$(foreach d,05 10 15 25 80, \
			$(THESIS_DIR)/results/figures/model/intervention_effects/.$(d)_$(MEASURE_TIME)) \
		$(foreach d,05 10 15 25 80, \
			$(THESIS_DIR)/results/figures/model/intervention_collective_ranking/.$(d)_$(MEASURE_TIME)) \
		$(foreach d,05 10 15 25 80, \
			$(THESIS_DIR)/results/figures/model/intervention_collective_effect/.$(d)_$(MEASURE_TIME)) \
		$(foreach d,05 10 15 25 80, \
			$(THESIS_DIR)/results/figures/model/intervention_effect_distribution/.$(d)_$(MEASURE_TIME)) \
		$(THESIS_DIR)/results/figures/model/intervention_collective_ranking/.$(MEASURE_TIME) \
		$(THESIS_DIR)/results/figures/model/intervention_individual_ranking/.$(MEASURE_TIME) \
		$(THESIS_DIR)/results/figures/model/directional_differentials/ideology.pdf \
		$(THESIS_DIR)/results/figures/model/directional_differentials/rank_no_structure.pdf \
		$(THESIS_DIR)/results/figures/model/directional_differentials/pairwise_no_structure.pdf \
		$(THESIS_DIR)/results/figures/model/interaction_matrix/full_asym_ising_no_structure.pdf \
		$(THESIS_DIR)/results/figures/model/interaction_matrix/full_sym_ising_no_structure.pdf \
		$(THESIS_DIR)/results/figures/model/ideology_fit/conservative_interaction_matrix.pdf \
		$(THESIS_DIR)/results/figures/model/ideology_fit/liberal_interaction_matrix.pdf \
		$(THESIS_DIR)/results/figures/model/ideology_fit/network.pdf \
		$(THESIS_DIR)/results/figures/model/network.pdf \
		$(THESIS_DIR)/results/figures/model_fit/regularisation_ebic.pdf \
		$(THESIS_DIR)/results/figures/model/heterogeneous_effects/climate_policy_treedepth_3.pdf \
		$(THESIS_DIR)/results/figures/model/heterogeneous_effects/climate_policy_treedepth_4.pdf

THESIS_FIGURES_MODEL_CALIBRATION := \
		$(THESIS_DIR)/results/figures/model_fit/edge_accuracy.pdf \
		$(THESIS_DIR)/results/figures/model_fit/ideology_edge_accuracy.pdf \
		$(THESIS_DIR)/results/figures/model_fit/high_relative_entropy.pdf \
		$(THESIS_DIR)/results/figures/model_fit/selection_probability.pdf \
		$(THESIS_DIR)/results/figures/model_fit/transition_reliability.pdf \
		$(THESIS_DIR)/results/figures/model_fit/mean_relative_entropy.pdf \
		$(THESIS_DIR)/results/figures/model_fit/kl_difference_dist.pdf \
		$(THESIS_DIR)/results/figures/model_fit/kl_difference_examples.pdf \
		$(THESIS_DIR)/results/figures/model_fit/interaction_heatmap.pdf \
		$(THESIS_DIR)/results/figures/model_fit/ideology_interaction_heatmap.pdf

THESIS_FIGURES_METHODS := \
		$(THESIS_DIR)/results/figures/methods/intervention_strengths.pdf

THESIS_FIGURES_ASYMMETRY_RESULTS := \
		$(THESIS_DIR)/results/figures/asymmetry_results/effect_of_asymmetry_politics.pdf \
		$(THESIS_DIR)/results/figures/asymmetry_results/effect_of_asymmetry_cc_worry.pdf \
		$(THESIS_DIR)/results/figures/asymmetry_results/intervention_strength_compare.pdf \
		$(THESIS_DIR)/results/figures/asymmetry_results/outbound_effects_5.pdf \
		$(THESIS_DIR)/results/figures/asymmetry_results/outbound_effects_10.pdf \
		$(THESIS_DIR)/results/figures/asymmetry_results/outbound_effect_of_asymmetry.pdf \
		$(THESIS_DIR)/results/figures/asymmetry_results/inbound_effects.pdf
		

THESIS_FIGURES_DATASET := \
		$(THESIS_DIR)/results/figures/dataset/participation.pdf \
		$(THESIS_DIR)/results/figures/dataset/response_eventplot.pdf \
		$(THESIS_DIR)/results/figures/dataset/interresponse_times.pdf \
		$(THESIS_DIR)/results/figures/dataset/validation_switchpoints.pdf \
		$(THESIS_DIR)/results/figures/dataset/full_subset_partial_corr.pdf \
		$(THESIS_DIR)/results/figures/dataset/full_subset_var.pdf \
		$(THESIS_DIR)/results/figures/dataset/full_subset_dendrogram.pdf \
		$(THESIS_DIR)/results/figures/dataset/reduced_subset_partial_corr.pdf \
		$(THESIS_DIR)/results/figures/dataset/marginal_distributions.pdf \
		$(THESIS_DIR)/results/figures/dataset/likert_7_binarisation_probability.pdf \
		$(THESIS_DIR)/results/figures/dataset/transition_probability.pdf

THESIS_DIAGRAMS := \
		$(THESIS_DIR)/diagrams/modelling_interventions/intervention.svg \
		$(THESIS_DIR)/diagrams/modelling_interventions/intervention_baseline_activation.svg \
		$(THESIS_DIR)/diagrams/survey_database/database.svg

THESIS_FIGURES := \
		$(THESIS_FIGURES_MODEL) \
		$(THESIS_FIGURES_METHODS) \
		$(THESIS_FIGURES_MODEL_CALIBRATION) \
		$(THESIS_FIGURES_DATASET) \
		$(THESIS_FIGURES_ASYMMETRY_RESULTS) \
		$(THESIS_DIAGRAMS)
		#$(THESIS_FIGURES_MODEL_FIT_STRATIFICATION)



THESIS_VERIFICATION_FILES := \
		$(THESIS_DIR)/results/verification/model/all_interventions.txt \
		$(THESIS_DIR)/results/verification/model/all_interventions.txt

THESIS_TYPST_DEPS := \
		$(THESIS_DIR)/main.typ \
		$(THESIS_DIR)/sections/abstract.typ \
		$(THESIS_DIR)/sections/notation.typ \
		$(THESIS_DIR)/sections/introduction.typ \
		$(THESIS_DIR)/sections/asymmetric_belief_system.typ \
		$(THESIS_DIR)/sections/methods.typ \
		$(THESIS_DIR)/sections/calibration.typ \
		$(THESIS_DIR)/sections/asymmetry_results.typ \
		$(THESIS_DIR)/sections/heterogeneity_results.typ \
		$(THESIS_DIR)/sections/discussion.typ \
		$(THESIS_DIR)/sections/dataset.typ \
		$(THESIS_DIR)/sections/literature_review.typ \
		$(THESIS_DIR)/sections/conclusion.typ \
		$(THESIS_DIR)/references.bib


THESIS_DEPS := \
		$(THESIS_TYPST_DEPS) \
		$(THESIS_DATA_DEPS) \
		$(THESIS_FIGURES) \
		$(THESIS_VERIFICATION_FILES)

QUIET ?= 1
ifeq ($(QUIET),1)
	QUIET_FLAG := --quiet
else
	QUIET_FLAG := --no-quiet
endif

# ==== Report
outputs/reports/thesis.pdf: $(THESIS_DEPS)
	@echo ${TYPST_PACKAGE_PATH}
	@typst compile $(THESIS_DIR)/main.typ $@

# Results, figures, data
$(THESIS_DIR)/results/data/dataset_metadata.json: \
			$(PKG_PATH)/cli/info.py \
			${CA_RAW_ASSETS}/w1w2w3w4w5_indices_weights_jul12_2022.parquet \
			${CA_RAW_ASSETS}/w6_cleaned_weights_june12_2023.parquet \
			| $(THESIS_DIR)/results/data
	@uv run cadata info dataset --output $@

# === Figures
# +++ Section: Methods
$(THESIS_DIR)/results/figures/methods/binarisation/distribution.pdf: \
			$(THESIS_DIR)/scripts/sec-methods/binarisation_distribution.py \
			$(PKG_PATH)/visualisation.py \
			| $(THESIS_DIR)/results/figures/methods/binarisation
	@uv run $<

$(THESIS_DIR)/results/figures/methods/regularisation_sparsity.pdf: \
			$(THESIS_DIR)/scripts/sec-methods/regularisation_sparsity_plot.py \
			$(THESIS_DIR)/results/data/methods/regularisation_sparsity.npz \
			| $(THESIS_DIR)/results/figures/methods
	@uv run $<

$(THESIS_DIR)/results/figures/methods/binarisation: | $(THESIS_DIR)/results/figures/methods
	@mkdir -p $@

	

$(THESIS_DIR)/results/figures/methods: | $(THESIS_DIR)/results/figures
	@mkdir -p $@

# +++ Section: Methods
$(THESIS_DIR)/results/figures/methods/intervention_strengths.pdf: \
			$(THESIS_DIR)/scripts/sec-methods/intervention_strengths_diagram.py \
			$(PKG_PATH)/visualisation.py \
			| $(THESIS_DIR)/results/figures/methods
	@uv run $<

# +++ Model calibration
$(THESIS_DIR)/results/figures/model_fit/ideology_edge_accuracy.pdf: \
			$(THESIS_DIR)/scripts/sec-model/edge_accuracy_ideology.py \
			$(THESIS_DIR)/results/data/model/ideology_bootstrapped_fit/liberal.npz \
			$(THESIS_DIR)/results/data/model/ideology_bootstrapped_fit/conservative.npz \
			$(PKG_PATH)/visualisation.py \
			| $(THESIS_DIR)/results/figures/model_fit
	@uv run $<

$(THESIS_DIR)/results/figures/model_fit/edge_accuracy.pdf: \
			$(THESIS_DIR)/scripts/sec-model/edge_accuracy.py \
			$(THESIS_DIR)/results/data/model/bootstrapped_fit/ising_no_structure.npz \
			$(THESIS_DIR)/results/data/model/bootstrapped_fit/sym_ising_no_structure.npz \
			$(PKG_PATH)/visualisation.py \
			| $(THESIS_DIR)/results/figures/model_fit
	@uv run $<

$(THESIS_DIR)/results/figures/model_fit/selection_probability.pdf: \
			$(THESIS_DIR)/scripts/sec-model/selection_proportion.py \
			$(THESIS_DIR)/results/data/model/bootstrapped_fit/ising_no_structure.npz \
			$(THESIS_DIR)/results/data/model/bootstrapped_fit/sym_ising_no_structure.npz \
			$(PKG_PATH)/visualisation.py \
			| $(THESIS_DIR)/results/figures/model_fit
	@uv run $<

$(THESIS_DIR)/results/figures/model_fit/transition_reliability.pdf: \
			$(THESIS_DIR)/scripts/sec-calibration/transition_reliability.py \
			$(THESIS_DIR)/results/data/model_fit/optimised_regularisation.json \
			$(THESIS_DIR)/results/data/methods/binarisation_sigma.json \
			${CA_BUILT_ASSETS}/reduced_no_imputation/metadata.json \
			$(PKG_PATH)/visualisation.py \
			| $(THESIS_DIR)/results/figures/model_fit
	@uv run $<

$(THESIS_DIR)/results/figures/model_fit/mean_relative_entropy.pdf: \
			$(THESIS_DIR)/scripts/sec-calibration/mean_relative_entropy.py \
			$(THESIS_DIR)/results/data/model_fit/optimised_regularisation.json \
			$(THESIS_DIR)/results/data/methods/binarisation_sigma.json \
			${CA_BUILT_ASSETS}/reduced_no_imputation/metadata.json \
			$(PKG_PATH)/visualisation.py \
			| $(THESIS_DIR)/results/figures/model_fit
	@uv run $<

$(THESIS_DIR)/results/figures/model_fit/kl_difference_dist.pdf: \
			$(THESIS_DIR)/scripts/sec-calibration/difference_relative_entropy.py \
			$(THESIS_DIR)/results/data/model_fit/optimised_regularisation.json \
			$(THESIS_DIR)/results/data/methods/binarisation_sigma.json \
			${CA_BUILT_ASSETS}/reduced_no_imputation/metadata.json \
			$(PKG_PATH)/visualisation.py \
			| $(THESIS_DIR)/results/figures/model_fit
	@uv run $<

$(THESIS_DIR)/results/figures/model_fit/kl_difference_examples.pdf: \
			$(THESIS_DIR)/scripts/sec-calibration/relative_entropy_difference_examples.py \
			$(THESIS_DIR)/results/data/model_fit/optimised_regularisation.json \
			$(THESIS_DIR)/results/data/methods/binarisation_sigma.json \
			${CA_BUILT_ASSETS}/reduced_no_imputation/metadata.json \
			$(PKG_PATH)/visualisation.py \
			| $(THESIS_DIR)/results/figures/model_fit
	@uv run $<

$(THESIS_DIR)/results/figures/model_fit/interaction_heatmap.pdf: \
			$(THESIS_DIR)/scripts/sec-calibration/interaction_heatmaps.py \
			$(THESIS_DIR)/results/data/model/fit_full_asym_ising_no_structure.npz \
			$(THESIS_DIR)/results/data/model/fit_full_sym_ising_no_structure.npz \
			$(PKG_PATH)/visualisation.py \
			| $(THESIS_DIR)/results/figures/model_fit
	@uv run $<

$(THESIS_DIR)/results/figures/model_fit/ideology_interaction_heatmap.pdf: \
			$(THESIS_DIR)/scripts/sec-calibration/ideology_interaction_heatmaps.py \
			$(THESIS_DIR)/results/data/model/ideology_fit_conservative.npz \
			$(THESIS_DIR)/results/data/model/ideology_fit_liberal.npz \
			$(PKG_PATH)/visualisation.py \
			| $(THESIS_DIR)/results/figures/model_fit
	@uv run $<

$(THESIS_DIR)/results/figures/model_fit/high_relative_entropy.pdf: \
			$(THESIS_DIR)/scripts/sec-model/relative_entropy.py \
			$(THESIS_DIR)/results/data/model_fit/optimised_regularisation.json \
			$(THESIS_DIR)/results/data/methods/binarisation_sigma.json \
			${CA_BUILT_ASSETS}/reduced_no_imputation/metadata.json \
			$(PKG_PATH)/visualisation.py \
			| $(THESIS_DIR)/results/figures/model_fit
	@uv run $<

# +++ Section: Asymmetry results
$(THESIS_DIR)/results/figures/asymmetry_results/effect_of_asymmetry_politics.pdf: \
			$(THESIS_DIR)/scripts/sec-asymmetry-results/effect_of_asymmetry_politics.py \
			$(THESIS_DIR)/results/data/model/all_interventions/ising_00.npz \
			$(THESIS_DIR)/results/data/model/all_interventions/ising_05.npz \
			$(THESIS_DIR)/results/data/model/all_interventions/ising_10.npz \
			$(THESIS_DIR)/results/data/model/all_interventions/ising_25.npz \
			$(THESIS_DIR)/results/data/model/all_interventions/sym_ising_00.npz \
			$(THESIS_DIR)/results/data/model/all_interventions/sym_ising_05.npz \
			$(THESIS_DIR)/results/data/model/all_interventions/sym_ising_10.npz \
			$(THESIS_DIR)/results/data/model/all_interventions/sym_ising_25.npz \
			$(PKG_PATH)/visualisation.py \
			| $(THESIS_DIR)/results/figures/asymmetry_results
	@uv run $<

$(THESIS_DIR)/results/figures/asymmetry_results/effect_of_asymmetry_cc_worry.pdf: \
			$(THESIS_DIR)/scripts/sec-asymmetry-results/effect_of_asymmetry_cc_worry.py \
			$(THESIS_DIR)/results/data/model/all_interventions/ising_00.npz \
			$(THESIS_DIR)/results/data/model/all_interventions/ising_05.npz \
			$(THESIS_DIR)/results/data/model/all_interventions/ising_10.npz \
			$(THESIS_DIR)/results/data/model/all_interventions/ising_25.npz \
			$(THESIS_DIR)/results/data/model/all_interventions/sym_ising_00.npz \
			$(THESIS_DIR)/results/data/model/all_interventions/sym_ising_05.npz \
			$(THESIS_DIR)/results/data/model/all_interventions/sym_ising_10.npz \
			$(THESIS_DIR)/results/data/model/all_interventions/sym_ising_25.npz \
			$(PKG_PATH)/visualisation.py \
			| $(THESIS_DIR)/results/figures/asymmetry_results
	@uv run $<

$(THESIS_DIR)/results/figures/asymmetry_results/outbound_effects_%.pdf: \
			$(PKG_PATH)/cli/visualisation/compare_outbound_int_effect.py \
			$(PKG_PATH)/visualisation.py \
			$(THESIS_DIR)/results/data/model/all_interventions/ising_00.npz \
			$(THESIS_DIR)/results/data/model/all_interventions/ising_25.npz \
			$(THESIS_DIR)/results/data/model/all_interventions/sym_ising_00.npz \
			$(THESIS_DIR)/results/data/model/all_interventions/sym_ising_25.npz \
			| $(THESIS_DIR)/results/figures/asymmetry_results
	uv run cadata plot compare-outbound-effects \
		--output-dir $(@D) \
		--data-dir $(THESIS_DIR)/results/data/model/all_interventions \
		--point-of-intervention-idx 4 \
		--point-of-intervention-idx 2 \
		--point-of-intervention-idx 5 \
		--delta 2.5 \
		-z 1.96 \
		--measure-time $*

$(THESIS_DIR)/results/figures/asymmetry_results/inbound_effects.pdf: \
			$(THESIS_DIR)/scripts/sec-asymmetry-results/inbound_effects.py \
			$(PKG_PATH)/visualisation.py \
			$(THESIS_DIR)/results/data/model/all_interventions/ising_00.npz \
			$(THESIS_DIR)/results/data/model/all_interventions/ising_25.npz \
			$(THESIS_DIR)/results/data/model/all_interventions/sym_ising_00.npz \
			$(THESIS_DIR)/results/data/model/all_interventions/sym_ising_25.npz \
			| $(THESIS_DIR)/results/figures/asymmetry_results
	@uv run $<
	

$(THESIS_DIR)/results/figures/asymmetry_results/outbound_effect_of_asymmetry.pdf: \
			$(THESIS_DIR)/scripts/sec-asymmetry-results/outbound_effect_of_asymmetry.py \
			$(PKG_PATH)/visualisation.py \
			$(THESIS_DIR)/results/data/model/all_interventions/ising_00.npz \
			$(THESIS_DIR)/results/data/model/all_interventions/ising_25.npz \
			$(THESIS_DIR)/results/data/model/all_interventions/sym_ising_00.npz \
			$(THESIS_DIR)/results/data/model/all_interventions/sym_ising_25.npz \
			| $(THESIS_DIR)/results/figures/asymmetry_results
	@uv run $<

$(THESIS_DIR)/results/figures/asymmetry_results/intervention_strength_compare.pdf: \
			$(PKG_PATH)/cli/visualisation/intervention_strength_relationship.py \
			$(PKG_PATH)/visualisation.py \
			$(THESIS_DIR)/results/data/model/all_interventions/ising_00.npz \
			$(THESIS_DIR)/results/data/model/all_interventions/ising_05.npz \
			$(THESIS_DIR)/results/data/model/all_interventions/ising_25.npz \
			$(THESIS_DIR)/results/data/model/all_interventions/sym_ising_00.npz \
			$(THESIS_DIR)/results/data/model/all_interventions/sym_ising_05.npz \
			$(THESIS_DIR)/results/data/model/all_interventions/sym_ising_25.npz \
			| $(THESIS_DIR)/results/figures/model/intervention_effects
	uv run cadata plot compare-intervention-strengths \
		--output-dir $(@D) \
		--data-dir $(THESIS_DIR)/results/data/model/all_interventions \
		--point-of-intervention-idx 0 \
		--point-of-intervention-idx 2 \
		--point-of-intervention-idx 5 \
		--delta 0.5 \
		--delta 2.5 \
		-z 1.96 \
		--measure-time $(MEASURE_TIME)

$(THESIS_DIR)/results/figures/asymmetry_results: | $(THESIS_DIR)/results/figures
	@mkdir -p $@

# +++ Section: Model
$(THESIS_DIR)/results/figures/model/transition_probability_example.pdf: \
			$(THESIS_DIR)/scripts/sec-model/transition_prob_example.py \
			$(PKG_PATH)/visualisation.py \
			| $(THESIS_DIR)/results/figures/model
	@uv run $<

$(THESIS_DIR)/results/figures/model/ideology_fit/%_interaction_matrix.pdf: \
			$(THESIS_DIR)/results/data/model/ideology_fit_%.npz \
			${PKG_PATH}/cli/visualisation/interaction_heatmap.py \
			| $(THESIS_DIR)/results/figures/model/ideology_fit
	@uv run cadata plot interaction-heatmap \
		--model $< \
		--output $@ \
		--model-type ising

$(THESIS_DIR)/results/figures/model/ideology_fit/network.pdf: \
			$(THESIS_DIR)/results/data/model/ideology_fit_conservative.npz \
			$(THESIS_DIR)/results/data/model/ideology_fit_liberal.npz \
			${PKG_PATH}/cli/visualisation/ideology_network.py \
			| $(THESIS_DIR)/results/figures/model/ideology_fit
	@uv run cadata plot ideology-networks \
		--conservative-model $(THESIS_DIR)/results/data/model/ideology_fit_conservative.npz \
		--liberal-model $(THESIS_DIR)/results/data/model/ideology_fit_liberal.npz \
		--output $@ \
		--model-type ising \
		--seed 20260623

$(THESIS_DIR)/results/figures/model/network.pdf: \
			$(THESIS_DIR)/results/data/model/fit_full_asym_ising_no_structure.npz \
			$(THESIS_DIR)/results/data/model/fit_full_sym_ising_no_structure.npz \
			${PKG_PATH}/cli/visualisation/network.py \
			| $(THESIS_DIR)/results/figures/model/network
	uv run cadata plot network \
		--sym-model $(THESIS_DIR)/results/data/model/fit_full_sym_ising_no_structure.npz \
		--asym-model $(THESIS_DIR)/results/data/model/fit_full_asym_ising_no_structure.npz \
		--output $@ \
		--seed 20260623

$(THESIS_DIR)/results/figures/model/network: | $(THESIS_DIR)/results/figures/model
	@mkdir -p $@


$(THESIS_DIR)/results/figures/model/ideology_fit: | $(THESIS_DIR)/results/figures/model
	@mkdir -p $@

$(THESIS_DIR)/results/figures/model/intervention_effects: | $(THESIS_DIR)/results/figures/model
	@mkdir -p $@


$(THESIS_DIR)/results/figures/model/intervention_effects/.%_$(MEASURE_TIME): \
			$(PKG_PATH)/cli/visualisation/intervention_mean_int_effect.py \
			$(PKG_PATH)/visualisation.py \
			$(THESIS_DIR)/results/data/model/all_interventions/ising_00.npz \
			$(THESIS_DIR)/results/data/model/all_interventions/ising_%.npz \
			$(THESIS_DIR)/results/data/model/all_interventions/sym_ising_00.npz \
			$(THESIS_DIR)/results/data/model/all_interventions/sym_ising_%.npz \
			| $(THESIS_DIR)/results/figures/model/intervention_effects
	uv run cadata plot intervention-mean-effects \
		--output-dir $(@D) \
		--data-dir $(THESIS_DIR)/results/data/model/all_interventions \
		--delta-str $* \
		-z 1.96 \
		--measure-time $(MEASURE_TIME) && \
	touch $@

$(THESIS_DIR)/results/figures/model/intervention_collective_ranking: | $(THESIS_DIR)/results/figures/model
	mkdir -p $@


$(THESIS_DIR)/results/figures/model/intervention_collective_ranking/.%_$(MEASURE_TIME): \
			$(PKG_PATH)/cli/visualisation/intervention_mean_collective_ranking.py \
			$(PKG_PATH)/visualisation.py \
			$(THESIS_DIR)/results/data/model/all_interventions/ising_%.npz \
			$(THESIS_DIR)/results/data/model/all_interventions/sym_ising_%.npz \
			| $(THESIS_DIR)/results/figures/model/intervention_collective_ranking
	uv run cadata plot intervention-mean-collective-rank \
		--output-dir $(@D) \
		--data-dir $(THESIS_DIR)/results/data/model/all_interventions \
		--delta-str $* \
		-z 1.96 \
		--measure-time $(MEASURE_TIME) && \
	touch $@

$(THESIS_DIR)/results/figures/model/intervention_collective_ranking/.$(MEASURE_TIME): \
			$(PKG_PATH)/cli/visualisation/intervention_mean_collective_ranking_comb.py \
			$(PKG_PATH)/visualisation.py \
			$(THESIS_DIR)/results/data/model/all_interventions/ising_05.npz \
			$(THESIS_DIR)/results/data/model/all_interventions/ising_25.npz \
			$(THESIS_DIR)/results/data/model/all_interventions/sym_ising_05.npz \
			$(THESIS_DIR)/results/data/model/all_interventions/sym_ising_25.npz \
			| $(THESIS_DIR)/results/figures/model/intervention_collective_ranking
	uv run cadata plot intervention-mean-collective-rank-comb \
		--output-dir $(@D) \
		--data-dir $(THESIS_DIR)/results/data/model/all_interventions \
		--intervention weak \
		--intervention strong \
		--asym-results $(THESIS_DIR)/results/data/model/all_interventions/ising_05.npz \
		--asym-results $(THESIS_DIR)/results/data/model/all_interventions/ising_25.npz \
		--sym-results $(THESIS_DIR)/results/data/model/all_interventions/sym_ising_05.npz \
		--sym-results $(THESIS_DIR)/results/data/model/all_interventions/sym_ising_25.npz \
		-z 1.96 \
		--measure-time $(MEASURE_TIME) && \
	touch $@

$(THESIS_DIR)/results/figures/model/intervention_individual_ranking: | $(THESIS_DIR)/results/figures/model
	mkdir -p $@


$(THESIS_DIR)/results/figures/model/intervention_individual_ranking/.$(MEASURE_TIME): \
			$(PKG_PATH)/cli/visualisation/intervention_mean_individual_ranking.py \
			$(PKG_PATH)/visualisation.py \
			$(THESIS_DIR)/results/data/model/all_interventions/ising_05.npz \
			$(THESIS_DIR)/results/data/model/all_interventions/ising_25.npz \
			| $(THESIS_DIR)/results/figures/model/intervention_individual_ranking
	uv run cadata plot intervention-mean-individual-rank \
		--output-dir $(@D) \
		--data-dir $(THESIS_DIR)/results/data/model/all_interventions \
		--intervention weak \
		--intervention strong \
		-z 1.0 \
		--measure-time $(MEASURE_TIME) && \
	touch $@

$(THESIS_DIR)/results/figures/model/intervention_collective_effect: | $(THESIS_DIR)/results/figures/model
	mkdir -p $@


$(THESIS_DIR)/results/figures/model/intervention_collective_effect/.%_$(MEASURE_TIME): \
			$(PKG_PATH)/cli/visualisation/intervention_mean_collective_effect.py \
			$(PKG_PATH)/visualisation.py \
			$(THESIS_DIR)/results/data/model/all_interventions/ising_%.npz \
			$(THESIS_DIR)/results/data/model/all_interventions/sym_ising_%.npz \
			| $(THESIS_DIR)/results/figures/model/intervention_collective_effect
	uv run cadata plot intervention-mean-collective-effect \
		--output-dir $(@D) \
		--data-dir $(THESIS_DIR)/results/data/model/all_interventions \
		--delta-str $* \
		-z 1.96 \
		--measure-time $(MEASURE_TIME) && \
	touch $@

$(THESIS_DIR)/results/figures/model/intervention_effect_distribution: | $(THESIS_DIR)/results/figures/model
	mkdir -p $@


$(THESIS_DIR)/results/figures/model/intervention_effect_distribution/.%_$(MEASURE_TIME): \
			$(PKG_PATH)/cli/visualisation/intervention_effect_distribution.py \
			$(PKG_PATH)/visualisation.py \
			$(THESIS_DIR)/results/data/model/all_interventions/ising_00.npz \
			$(THESIS_DIR)/results/data/model/all_interventions/ising_%.npz \
			$(THESIS_DIR)/results/data/model/all_interventions/sym_ising_00.npz \
			$(THESIS_DIR)/results/data/model/all_interventions/sym_ising_%.npz \
			| $(THESIS_DIR)/results/figures/model/intervention_effect_distribution
	uv run cadata plot intervention-effect-distribution \
		--output-dir $(@D) \
		--data-dir $(THESIS_DIR)/results/data/model/all_interventions \
		--delta-str $* \
		--measure-time $(MEASURE_TIME) && \
	touch $@

$(THESIS_DIR)/results/figures/model/directional_differentials/ideology.pdf: \
			$(THESIS_DIR)/results/data/model/ideology_bootstrapped_fit/liberal.npz \
			$(THESIS_DIR)/results/data/model/ideology_bootstrapped_fit/conservative.npz \
			$(THESIS_DIR)/results/data/model/ideology_fit_liberal.npz \
			$(THESIS_DIR)/results/data/model/ideology_fit_conservative.npz \
			${PKG_PATH}/cli/visualisation/directional_differential_ideology.py \
			| $(THESIS_DIR)/results/figures/model/directional_differentials
	@uv run cadata plot directional-diffs-ideology \
		--bootstrap-models-con $(THESIS_DIR)/results/data/model/ideology_bootstrapped_fit/conservative.npz \
		--bootstrap-models-lib $(THESIS_DIR)/results/data/model/ideology_bootstrapped_fit/liberal.npz \
		--full-model-con $(THESIS_DIR)/results/data/model/ideology_fit_conservative.npz \
		--full-model-lib $(THESIS_DIR)/results/data/model/ideology_fit_liberal.npz \
		--output $@ \


$(THESIS_DIR)/results/figures/model/directional_differentials/rank_%.pdf: \
			$(THESIS_DIR)/results/data/model/bootstrapped_fit/ising_%.npz \
			$(THESIS_DIR)/results/data/model/fit_full_asym_ising_no_structure.npz \
			${PKG_PATH}/cli/visualisation/directional_differential.py \
			| $(THESIS_DIR)/results/figures/model/directional_differentials
	uv run cadata plot directional-differentials \
		--bootstrap-models $< \
		--full-model $(THESIS_DIR)/results/data/model/fit_full_asym_ising_no_structure.npz \
		--output $@ \
		-z 1.645 \
		--kind rank

$(THESIS_DIR)/results/figures/model/directional_differentials/pairwise_%.pdf: \
			$(THESIS_DIR)/results/data/model/bootstrapped_fit/ising_%.npz \
			$(THESIS_DIR)/results/data/model/fit_full_asym_ising_no_structure.npz \
			${PKG_PATH}/cli/visualisation/directional_differential.py \
			| $(THESIS_DIR)/results/figures/model/directional_differentials
	uv run cadata plot directional-differentials \
		--bootstrap-models $< \
		--full-model $(THESIS_DIR)/results/data/model/fit_full_asym_ising_no_structure.npz \
		--output $@ \
		--kind pairwise

$(THESIS_DIR)/results/figures/model/directional_differentials: | $(THESIS_DIR)/results/figures/model
	@mkdir -p $@

$(THESIS_DIR)/results/figures/model/interaction_matrix/%.pdf: \
			$(THESIS_DIR)/results/data/model/fit_%.npz \
			${PKG_PATH}/cli/visualisation/interaction_heatmap.py \
			| $(THESIS_DIR)/results/figures/model/interaction_matrix
	@model=$$(uv run $(THESIS_DIR)/scripts/sec-model/plot_interaction_heatmap_parse_params.py $* model) && \
	uv run cadata plot interaction-heatmap \
		--model $< \
		--output $@ \
		--model-type $$model

$(THESIS_DIR)/results/figures/model/interaction_matrix: | $(THESIS_DIR)/results/figures/model
	@mkdir -p $@

$(THESIS_DIR)/results/figures/model_fit/regularisation_ebic.pdf: \
			$(THESIS_DIR)/results/data/model_fit/asym_ising_regularisation_ebic_full.npz \
			$(THESIS_DIR)/results/data/model_fit/sym_ising_regularisation_ebic_full.npz \
			${PKG_PATH}/cli/visualisation/regularisation_ebic.py \
			| $(THESIS_DIR)/results/figures/model_fit
	uv run cadata plot regularisation-ebic \
		--asym-results $(THESIS_DIR)/results/data/model_fit/asym_ising_regularisation_ebic_full.npz \
		--sym-results $(THESIS_DIR)/results/data/model_fit/sym_ising_regularisation_ebic_full.npz \
		-z 1.96 \
		--output $@


$(THESIS_DIR)/results/figures/model/heterogeneous_effects/climate_policy_treedepth_%.pdf: \
			$(THESIS_DIR)/results/data/model/all_interventions/ising_00.npz \
			$(THESIS_DIR)/results/data/model/all_interventions_activation_probability/ising_00_5.npz \
			$(THESIS_DIR)/results/data/model/all_interventions_activation_probability/ising_05_5.npz \
			$(THESIS_DIR)/results/data/model/all_interventions_activation_probability/ising_25_5.npz \
			${PKG_PATH}/cli/visualisation/heterogeneous_intervention_effects.py \
			| $(THESIS_DIR)/results/figures/model/heterogeneous_effects
	uv run cadata plot identify-effective-personas \
		--simulation-results $(THESIS_DIR)/results/data/model/all_interventions/ising_00.npz \
		--activation-probability-null $(THESIS_DIR)/results/data/model/all_interventions_activation_probability/ising_00_5.npz \
		--activation-probability-intervention $(THESIS_DIR)/results/data/model/all_interventions_activation_probability/ising_25_5.npz \
		--intervention strong \
		--target-spin-idx 7 \
		--max-tree-depth $* \
		--output $@

$(THESIS_DIR)/results/figures/model/heterogeneous_effects: | $(THESIS_DIR)/results/figures/model
	@mkdir -p $@

			

# +++ Section: Dataset
$(THESIS_DIR)/results/figures/dataset/transition_probability.pdf: \
			$(THESIS_DIR)/scripts/sec-dataset/transition_probability.py \
			$(THESIS_DIR)/results/data/methods/binarisation_sigma.json \
			${CA_BUILT_ASSETS}/reduced_no_imputation/metadata.json \
			$(PKG_PATH)/visualisation.py \
			| $(THESIS_DIR)/results/figures/model_fit
	@uv run $<

$(THESIS_DIR)/results/figures/dataset/likert_7_binarisation_probability.pdf: \
			$(THESIS_DIR)/scripts/sec-dataset/likert_binarisation_probabilities.py \
			$(THESIS_DIR)/results/data/methods/binarisation_sigma.json \
			| $(THESIS_DIR)/results/figures/dataset
	@uv run $<

$(THESIS_DIR)/results/figures/dataset/marginal_distributions.pdf: \
			$(THESIS_DIR)/scripts/sec-dataset/marginal_distributions_reduced.py \
			${CA_BUILT_ASSETS}/reduced_no_imputation/metadata.json \
			| $(THESIS_DIR)/results/figures/dataset
	@uv run $<

$(THESIS_DIR)/results/figures/dataset/reduced_subset_partial_corr.pdf: \
			$(THESIS_DIR)/scripts/sec-dataset/partial_correlation_reduced.py \
			${CA_BUILT_ASSETS}/reduced_no_imputation/metadata.json \
			| $(THESIS_DIR)/results/figures/dataset
	@uv run $<

$(THESIS_DIR)/results/figures/dataset/full_subset_dendrogram.pdf: \
			$(THESIS_DIR)/scripts/sec-dataset/hclust_full.py \
			${CA_BUILT_ASSETS}/reduced_no_imputation/metadata.json \
			| $(THESIS_DIR)/results/figures/dataset
	@uv run $<

$(THESIS_DIR)/results/figures/dataset/full_subset_var.pdf: \
			$(THESIS_DIR)/scripts/sec-dataset/var_full.py \
			${CA_BUILT_ASSETS}/reduced_no_imputation/metadata.json \
			| $(THESIS_DIR)/results/figures/dataset
	@uv run $<

$(THESIS_DIR)/results/figures/dataset/full_subset_partial_corr.pdf: \
			$(THESIS_DIR)/scripts/sec-dataset/partial_correlation_full.py \
			${CA_BUILT_ASSETS}/reduced_no_imputation/metadata.json \
			| $(THESIS_DIR)/results/figures/dataset
	@uv run $<


$(THESIS_DIR)/results/figures/dataset/validation_switchpoints.pdf: \
			$(THESIS_DIR)/scripts/sec-dataset/validation_switchpoints.py \
			$(PKG_PATH)/visualisation.py \
			${CA_RAW_ASSETS}/w1w2w3w4w5_indices_weights_jul12_2022.parquet \
			| $(THESIS_DIR)/results/figures/dataset
	@uv run $<
			

$(THESIS_DIR)/results/figures/dataset/interresponse_times.pdf: \
			$(PKG_PATH)/cli/visualisation/interresponse_time.py \
			$(PKG_PATH)/visualisation.py \
			${CA_RAW_ASSETS}/w1w2w3w4w5_indices_weights_jul12_2022.parquet \
			${CA_RAW_ASSETS}/w6_cleaned_weights_june12_2023.parquet \
			| $(THESIS_DIR)/results/figures/dataset
	@uv run cadata plot interresponse-times --output $@


$(THESIS_DIR)/results/figures/dataset/response_eventplot.pdf: \
			$(PKG_PATH)/cli/visualisation/response_eventplot.py \
			$(PKG_PATH)/visualisation.py \
			${CA_RAW_ASSETS}/w1w2w3w4w5_indices_weights_jul12_2022.parquet \
			${CA_RAW_ASSETS}/w6_cleaned_weights_june12_2023.parquet \
			| $(THESIS_DIR)/results/figures/dataset
	@uv run cadata plot response-events --output $@

$(THESIS_DIR)/results/figures/dataset/participation.pdf: \
			$(THESIS_DIR)/scripts/sec-dataset/participation_plot.py \
			$(PKG_PATH)/visualisation.py \
			${CA_RAW_ASSETS}/w1w2w3w4w5_indices_weights_jul12_2022.parquet \
			${CA_RAW_ASSETS}/w6_cleaned_weights_june12_2023.parquet \
			| $(THESIS_DIR)/results/figures/dataset
	@uv run $<


# === Verification
# +++ Section: Model
# Pairwise interventions: intervene on s_i, measure state at s_j at time t.
$(THESIS_DIR)/results/verification/model/all_interventions.txt: \
			$(THESIS_DIR)/scripts/verification/model/all_interventions.py \
			$(THESIS_DIR)/results/data/model/all_interventions/ising_00.npz \
			$(THESIS_DIR)/results/data/model/all_interventions/ising_05.npz \
			$(THESIS_DIR)/results/data/model/all_interventions/ising_10.npz \
			$(THESIS_DIR)/results/data/model/all_interventions/sym_ising_00.npz \
			$(THESIS_DIR)/results/data/model/all_interventions/sym_ising_05.npz \
			$(THESIS_DIR)/results/data/model/all_interventions/sym_ising_10.npz \
			| $(THESIS_DIR)/results/verification/model
	@uv run $<

$(THESIS_DIR)/results/verification/model: | $(THESIS_DIR)/results/verification
	@mkdir -p $@


$(THESIS_DIR)/results/verification: | $(THESIS_DIR)/results
	@mkdir -p $@

	

# === Analysis results/data
# +++ Section: Methods
$(THESIS_DIR)/results/data/methods/binarisation_sigma.json: \
			$(THESIS_DIR)/scripts/sec-methods/choose_sigma.py \
			| $(THESIS_DIR)/results/data/methods
	@uv run $<

$(THESIS_DIR)/results/data/methods/regularisation_sparsity.npz: \
			$(THESIS_DIR)/scripts/sec-methods/regularisation_sparsity_measure.py \
			| $(THESIS_DIR)/results/data/methods
	@uv run $<

$(THESIS_DIR)/results/data/methods: | $(THESIS_DIR)/results/data
	@mkdir -p $@

# +++ Section: Model
$(THESIS_DIR)/results/data/model/ideology_bootstrapped_fit/%.npz: \
			${PKG_PATH}/cli/analysis/fit_bootstrapped_models.py \
			$(THESIS_DIR)/results/data/model_fit/optimised_regularisation.json \
			$(THESIS_DIR)/results/data/methods/binarisation_sigma.json \
			${CA_BUILT_ASSETS}/reduced_no_imputation/metadata.json \
			| $(THESIS_DIR)/results/data/model/ideology_bootstrapped_fit
	uv run cadata analysis fit-bootstrapped-ideology \
		--output $@ \
		--model-type ising \
		--ideology $* \
		--seed 202607262016 \
		--repeats 500 \
		--binarisation-kind gaussian \
		--marginalise \
		--lam-path $(THESIS_DIR)/results/data/model_fit/optimised_regularisation.json \
		--sigma-path $(THESIS_DIR)/results/data/methods/binarisation_sigma.json \
		$(QUIET_FLAG)

$(THESIS_DIR)/results/data/model/ideology_bootstrapped_fit: | $(THESIS_DIR)/results/data/model
	@mkdir -p $@

$(THESIS_DIR)/results/data/model/bootstrapped_fit/%.npz: \
			${PKG_PATH}/cli/analysis/fit_bootstrapped_models.py \
			$(THESIS_DIR)/results/data/model_fit/optimised_regularisation.json \
			$(THESIS_DIR)/results/data/methods/binarisation_sigma.json \
			${CA_BUILT_ASSETS}/reduced_no_imputation/metadata.json \
			| $(THESIS_DIR)/results/data/model/bootstrapped_fit
	@model=$$(uv run $(THESIS_DIR)/scripts/sec-model/fit_bootstrapped_parse_params.py $* model) && \
	uv run cadata analysis fit-bootstrapped \
		--output $@ \
		--model-type $$model \
		--seed 202606111547 \
		--repeats 500 \
		--binarisation-kind gaussian \
		--marginalise \
		--lam-path $(THESIS_DIR)/results/data/model_fit/optimised_regularisation.json \
		--sigma-path $(THESIS_DIR)/results/data/methods/binarisation_sigma.json \
		$(QUIET_FLAG)
		

$(THESIS_DIR)/results/data/model/bootstrapped_fit: | $(THESIS_DIR)/results/data/model
	@mkdir -p $@
		
				
# Pairwise interventions: intervene on s_i, measure state at s_j at time t.
$(THESIS_DIR)/results/data/model/all_interventions: | $(THESIS_DIR)/results/data/model
	@mkdir -p $@


$(THESIS_DIR)/results/data/model/all_interventions/%: \
			${PKG_PATH}/cli/analysis/all_interventions.py \
			$(THESIS_DIR)/results/data/model_fit/optimised_regularisation.json \
			$(THESIS_DIR)/results/data/methods/binarisation_sigma.json \
			${CA_BUILT_ASSETS}/reduced_no_imputation/metadata.json \
			| $(THESIS_DIR)/results/data/model/all_interventions
	@model=$$(uv run $(THESIS_DIR)/scripts/sec-model/all_interventions_parse_params.py $* model); \
	delta=$$(uv run $(THESIS_DIR)/scripts/sec-model/all_interventions_parse_params.py $* delta) && \
	uv run cadata analysis all-interventions \
		--output $@ \
		--model-type "$$model" \
		--seed 202605271053 \
		--repeats 500 \
		--marginalise \
		--binarisation-kind "gaussian" \
		--measure-time 15 \
		--intervention-delta $$delta \
		--sigma-path $(THESIS_DIR)/results/data/methods/binarisation_sigma.json \
		--lam-path $(THESIS_DIR)/results/data/model_fit/optimised_regularisation.json \
		$(QUIET_FLAG)

$(THESIS_DIR)/results/data/model/all_interventions_activation_probability/%_5.npz: \
			$(THESIS_DIR)/results/data/model/all_interventions/%.npz \
			${PKG_PATH}/cli/analysis/calculate_activation_probability.py \
			| $(THESIS_DIR)/results/data/model/all_interventions_activation_probability
	delta=$$(uv run $(THESIS_DIR)/scripts/sec-model/all_interventions_parse_params.py $*.npz delta) && \
	uv run cadata analysis calculate-activation-probability \
		--simulation-results $< \
		--intervention-delta $$delta \
		--measure-time 5 \
		--output $@

$(THESIS_DIR)/results/data/model/all_interventions_activation_probability: $(THESIS_DIR)/results/data/model
	@mkdir -p $@


$(THESIS_DIR)/results/data/model/fit_%.npz: \
			${PKG_PATH}/cli/analysis/fit_model.py \
			$(THESIS_DIR)/results/data/model_fit/optimised_regularisation.json \
			$(THESIS_DIR)/results/data/methods/binarisation_sigma.json \
			${CA_BUILT_ASSETS}/reduced_no_imputation/metadata.json \
			| $(THESIS_DIR)/results/data/model
	@filter_cond=$$(uv run $(THESIS_DIR)/scripts/sec-model/fit_model_parse_params.py $* filter); \
	model=$$(uv run $(THESIS_DIR)/scripts/sec-model/fit_model_parse_params.py $* model) && \
	uv run cadata analysis fit-model \
		--output $@ \
		--model-type $$model \
		$$filter_cond \
		--lam-path $(THESIS_DIR)/results/data/model_fit/optimised_regularisation.json \
		--sigma-path $(THESIS_DIR)/results/data/methods/binarisation_sigma.json \
		--binarisation-kind gaussian \
		--seed 202606181614


$(THESIS_DIR)/results/data/model/ideology_fit_conservative.npz: \
			${PKG_PATH}/cli/analysis/fit_model_by_ideology.py \
			$(THESIS_DIR)/results/data/model_fit/optimised_regularisation.json \
			$(THESIS_DIR)/results/data/methods/binarisation_sigma.json \
			${CA_BUILT_ASSETS}/reduced_no_imputation/metadata.json \
			| $(THESIS_DIR)/results/data/model
	@uv run cadata analysis fit-ideology-model \
		--output $@ \
		--metadata-output $(@D)/ideology_fit_conservative_metadata.json \
		--model-type ising \
		--ideology conservative \
		--lam-path $(THESIS_DIR)/results/data/model_fit/optimised_regularisation.json \
		--sigma-path $(THESIS_DIR)/results/data/methods/binarisation_sigma.json \
		--marginalise \
		--seed 202606222000

$(THESIS_DIR)/results/data/model/ideology_fit_liberal.npz: \
			${PKG_PATH}/cli/analysis/fit_model_by_ideology.py \
			$(THESIS_DIR)/results/data/model_fit/optimised_regularisation.json \
			$(THESIS_DIR)/results/data/methods/binarisation_sigma.json \
			${CA_BUILT_ASSETS}/reduced_no_imputation/metadata.json \
			| $(THESIS_DIR)/results/data/model
	@uv run cadata analysis fit-ideology-model \
		--output $@ \
		--metadata-output $(@D)/ideology_fit_liberal_metadata.json \
		--model-type ising \
		--ideology liberal \
		--lam-path $(THESIS_DIR)/results/data/model_fit/optimised_regularisation.json \
		--sigma-path $(THESIS_DIR)/results/data/methods/binarisation_sigma.json \
		--marginalise \
		--seed 202606222000
		

$(THESIS_DIR)/results/data/model_fit/optimised_regularisation.json: \
			${PKG_PATH}/cli/analysis/choose_regularisation_strength.py \
			$(THESIS_DIR)/results/data/model_fit/asym_ising_regularisation_ebic_full.npz \
			$(THESIS_DIR)/results/data/model_fit/sym_ising_regularisation_ebic_full.npz \
			$(THESIS_DIR)/results/data/model_fit/asym_ising_regularisation_ebic_conservative.npz \
			$(THESIS_DIR)/results/data/model_fit/asym_ising_regularisation_ebic_liberal.npz \
			| $(THESIS_DIR)/results/data/model_fit
	uv run cadata analysis choose-regularisation \
		--output $@ \
		--full-asym-ebic-results $(THESIS_DIR)/results/data/model_fit/asym_ising_regularisation_ebic_full.npz \
		--full-sym-ebic-results $(THESIS_DIR)/results/data/model_fit/sym_ising_regularisation_ebic_full.npz \
		--conservative-asym-ebic-results $(THESIS_DIR)/results/data/model_fit/asym_ising_regularisation_ebic_conservative.npz \
		--liberal-asym-ebic-results $(THESIS_DIR)/results/data/model_fit/asym_ising_regularisation_ebic_liberal.npz
			

$(THESIS_DIR)/results/data/model_fit/%_regularisation_ebic_full.npz: \
			${PKG_PATH}/cli/analysis/regularisation.py \
			${CA_BUILT_ASSETS}/reduced_no_imputation/metadata.json \
			$(THESIS_DIR)/results/data/methods/binarisation_sigma.json \
			| $(THESIS_DIR)/results/data/model_fit
	@model=$$(uv run $(THESIS_DIR)/scripts/sec-model-fit/regularisation_ebic_parse_params.py $*) && \
	uv run cadata analysis regularisation-ebic \
		--output $@ \
		--model-type $$model \
		--min -4 \
		--max -1.5 \
		-n 30 \
		--repeats 1 \
		--marginalise \
		--binarisation-kind gaussian \
		--non-zero-threshold 0.01 \
		--sigma-path $(THESIS_DIR)/results/data/methods/binarisation_sigma.json \
		--seed 202606191202 \
		$(QUIET_FLAG)

$(THESIS_DIR)/results/data/model_fit/%_regularisation_ebic_conservative.npz: \
			${PKG_PATH}/cli/analysis/regularisation.py \
			${CA_BUILT_ASSETS}/reduced_no_imputation/metadata.json \
			$(THESIS_DIR)/results/data/methods/binarisation_sigma.json \
			| $(THESIS_DIR)/results/data/model_fit
	@model=$$(uv run $(THESIS_DIR)/scripts/sec-model-fit/regularisation_ebic_parse_params.py $*) && \
	uv run cadata analysis regularisation-ebic \
		--output $@ \
		--model-type $$model \
		--subset conservative \
		--min -2.5 \
		--max -1 \
		-n 30 \
		--repeats 1 \
		--marginalise \
		--binarisation-kind gaussian \
		--non-zero-threshold 0.01 \
		--sigma-path $(THESIS_DIR)/results/data/methods/binarisation_sigma.json \
		--seed 202606191202 \
		$(QUIET_FLAG)

$(THESIS_DIR)/results/data/model_fit/%_regularisation_ebic_liberal.npz: \
			${PKG_PATH}/cli/analysis/regularisation.py \
			${CA_BUILT_ASSETS}/reduced_no_imputation/metadata.json \
			$(THESIS_DIR)/results/data/methods/binarisation_sigma.json \
			| $(THESIS_DIR)/results/data/model_fit
	@model=$$(uv run $(THESIS_DIR)/scripts/sec-model-fit/regularisation_ebic_parse_params.py $*) && \
	uv run cadata analysis regularisation-ebic \
		--output $@ \
		--model-type $$model \
		--subset liberal \
		--min -2.5 \
		--max -1 \
		-n 30 \
		--repeats 1 \
		--marginalise \
		--binarisation-kind gaussian \
		--non-zero-threshold 0.01 \
		--sigma-path $(THESIS_DIR)/results/data/methods/binarisation_sigma.json \
		--seed 202606191202 \
		$(QUIET_FLAG)



$(THESIS_DIR)/results/data: | $(THESIS_DIR)/results
	@mkdir -p $@

$(THESIS_DIR)/results/data/model: | $(THESIS_DIR)/results/data
	@mkdir -p $@

$(THESIS_DIR)/results/data/model_fit: | $(THESIS_DIR)/results/data
	@mkdir -p $@

$(THESIS_DIR)/results/figures/model: | $(THESIS_DIR)/results/figures
	@mkdir -p $@

$(THESIS_DIR)/results/figures/dataset: | $(THESIS_DIR)/results/figures
	@mkdir -p $@

$(THESIS_DIR)/results/figures/model_fit: | $(THESIS_DIR)/results/figures
	@mkdir -p $@

$(THESIS_DIR)/results/figures: | $(THESIS_DIR)/results
	@mkdir -p $@

$(THESIS_DIR)/results: 
	@mkdir -p $(THESIS_DIR)/results

