site_name: Intervening on Asymmetric Models of Internal Beliefs 
site_url: https://henry-zwart.github.io/msc_thesis/
repo_url: https://github.com/henry-zwart/msc_thesis/
nav:
  - Home: index.md
  - Research log: log.md
  - Glossary: glossary.md
theme:
  name: material
  features:
    - content.footnote.tooltips

plugins:
  - search
  - bibtex:
      bib_file: "references.bib"
      bib_by_default: false
markdown_extensions:
  - toc:
      toc_depth: 2
      permalink: true
  - admonition
  - footnotes
  - def_list
  - attr_list
  - tables
  - md_in_html
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css
  - stylesheets/extra.css
