---
title: "Quarto Basics"
format:
  html:
    code-fold: true
    page-layout: full
execute:
  echo: false
---

```{python}
from pathlib import Path

import numpy as np

import polars.selectors as cs

import matplotlib.pyplot as plt
import seaborn as sns

from statsmodels.multivariate.factor import Factor
from sklearn.decomposition import PCA

from climate_attitudes.settings import Config
from climate_attitudes.dataset import Dataset
from climate_attitudes.correlation import Correlation, filter_vars_by_abs_corr
from climate_attitudes import configure_mpl
from climate_attitudes.visualisation import plot_corr_with_dendro, plot_feature_dendro
from climate_attitudes.parallel_analysis import pa_random_eigs, pa_true_eigs
import climate_attitudes.datasets.full as full_ds
import climate_attitudes.datasets.reduced as reduced_ds
import climate_attitudes.datasets.reduced_no_imputation as reduced_no_imputation_ds

from climate_attitudes.feature_clustering import LinkageMethod

FONT_PATH = Path("../../fonts")
configure_mpl(FONT_PATH)

plt.rc("figure", dpi=100)
```

```{python}
#| tags: [parameters]

ds_name: str = "full"
```

```{python}
match ds_name:
    case "full":
        ds_spec = full_ds
    case "reduced":
        ds_spec = reduced_ds
    case "reduced_no_imputation":
        ds_spec = reduced_no_imputation_ds
    case _:
        raise RuntimeError(f"Unknown dataset: '{ds_name}'.")
```


```{python}
#| output: false
# Load data
config = Config(_env_file="../../.env")
dataset = Dataset.load(config, name=ds_name, with_imputation=False)
dataset_std = dataset.standardise(cs.exclude(*ds_spec.SURVEY_COLS))
resp = dataset.response.collect()
resp_std = dataset_std.response.collect()
```

# Pairwise correlation overview

Generally high Pearson correlations reflect common CC theme. Some variables have little to no correlation 
outside a restricted set (e.g. `soc_trust` & `soc_help`, or `ew5` & `ew6`).

Partial correlations are sparse, at least partially due to the large number of variables. A cluster of moderate--high correlation is maintained between the `cc4_X` and `cc5_X` questions.

For VAR: the contemporaneous GGM reflects the partial correlation heatmap; the temporal GGM is sparser, with some strong self-correlated questions, and others which are considerably weaker (e.g. `cc11`, `cc12`, `cc4_poorUS`, `cc4_wealthUS`).


::: {.panel-tabset}

## Pearson

```{python}
plot_corr_with_dendro(resp_std, kind=Correlation.PEARSON, no_cbar=True, x_categories=ds_spec.CATEGORIES, y_categories=ds_spec.CATEGORIES)
```

## Distance

```{python}
plot_corr_with_dendro(resp_std, kind=Correlation.DISTANCE_CORR, no_cbar=True, x_categories=ds_spec.CATEGORIES, y_categories=ds_spec.CATEGORIES)
```

## Partial

```{python}
plot_corr_with_dendro(resp_std, kind=Correlation.PARTIAL, no_cbar=True, x_categories=ds_spec.CATEGORIES, y_categories=ds_spec.CATEGORIES)
```

## Partial (regularised)

```{python}
plot_corr_with_dendro(resp_std, kind=Correlation.PARTIAL_GLASSO, no_cbar=True, x_categories=ds_spec.CATEGORIES, y_categories=ds_spec.CATEGORIES)
```

## VAR (Contemporaneous)

```{python}
plot_corr_with_dendro(resp_std, kind=Correlation.VAR_CONTEMPORANEOUS, no_cbar=True, x_categories=ds_spec.CATEGORIES, y_categories=ds_spec.CATEGORIES)
```

## VAR (Temporal)

```{python}
plot_corr_with_dendro(resp_std, kind=Correlation.VAR_TEMPORAL, no_cbar=True, x_categories=ds_spec.CATEGORIES, y_categories=ds_spec.CATEGORIES)
```

## VAR (Contemporaneous; regularised)

```{python}
plot_corr_with_dendro(resp_std, kind=Correlation.VAR_CONTEMPORANEOUS, no_cbar=True, x_categories=ds_spec.CATEGORIES, y_categories=ds_spec.CATEGORIES, regularised=True)
```

## VAR (Temporal; regularised)

```{python}
plot_corr_with_dendro(resp_std, kind=Correlation.VAR_TEMPORAL, no_cbar=True, x_categories=ds_spec.CATEGORIES, y_categories=ds_spec.CATEGORIES, regularised=True)
```

:::

<!--
## High-correlation variables (Pearson $\geq 0.5$)


Questions with high Pearson correlation all belong to either the `cc4/5_X` group, or `cvcc9_cc`. Three clusters emerge in the partial correlations between these variables:

+ `cvcc9_cc` and `cvcc9_cv`: 'People with the appropriate expertise should guide the response to CC/Covid'
+ `cc4_world`, `cc4_poorUS`, `cc3`, `cc6`: The `cc4_X` variables reflect epistemic positions regarding the current impacts of climate change. `cc3` reflects the current 'crisis-level' of climate change, and `cc6` the respondent's level of worry. 
+ `cc5_X`: These reflect epistemic positions on the future impacts of climate change.

Notably `cc4_world` is only strongly linked to `cc4_poorUS`, perhaps reflecting the belief that when climate change is impactful _in general_, poor communities bear the brunt of these impacts. 

The contemporaneous network clusters differently to the partial correlations in this case, and contains several negative weights, particularly associated with `cc3` (belief about the 'crisis-level' of CC). These negative weights are surprising (e.g., with `cc4_poorUS`), and perhaps reflect a form of bias due to the calculation process.

```{python}
plt.rc("figure", dpi=100)
```

```{python}
high_corr_cols, high_corr_idxes = filter_vars_by_abs_corr(resp_std, 0.5)
resp_std_high_corr = resp.select(*ds_spec.SURVEY_COLS, *high_corr_cols)
categories_high_corr = ds_spec.CATEGORIES[high_corr_idxes]
```

::: {.panel-tabset}

### Pearson
```{python}
plot_corr_with_dendro(resp_std_high_corr, kind=Correlation.PEARSON, no_cbar=True, x_categories=categories_high_corr, y_categories=categories_high_corr)
```

### Distance
```{python}
plot_corr_with_dendro(resp_std_high_corr, kind=Correlation.DISTANCE_CORR, no_cbar=True, x_categories=categories_high_corr, y_categories=categories_high_corr)
```

### Partial
```{python}
plot_corr_with_dendro(resp_std_high_corr, kind=Correlation.PARTIAL, no_cbar=True, x_categories=categories_high_corr, y_categories=categories_high_corr)
```

### Partial (regularised)
```{python}
plot_corr_with_dendro(resp_std_high_corr, kind=Correlation.PARTIAL_GLASSO, no_cbar=True, x_categories=categories_high_corr, y_categories=categories_high_corr)
```

### VAR (Contemporaneous)
```{python}
plot_corr_with_dendro(resp_std_high_corr, kind=Correlation.VAR_CONTEMPORANEOUS, no_cbar=True, x_categories=categories_high_corr, y_categories=categories_high_corr)
```

### VAR (Temporal)
```{python}
plot_corr_with_dendro(resp_std_high_corr, kind=Correlation.VAR_TEMPORAL, no_cbar=True, x_categories=categories_high_corr, y_categories=categories_high_corr)
```

:::

## High distance correlation (> 0.3)

```{python}
high_corr_cols, high_corr_idxes = filter_vars_by_abs_corr(resp_std, 0.25, kind=Correlation.DISTANCE_CORR)
resp_std_high_corr = resp.select(*ds_spec.SURVEY_COLS, *high_corr_cols)
categories_high_corr = ds_spec.CATEGORIES[high_corr_idxes]
```

::: {.panel-tabset}

### Pearson
```{python}
if high_corr_idxes.any():
    plot_corr_with_dendro(resp_std_high_corr, kind=Correlation.PEARSON, no_cbar=True, x_categories=categories_high_corr, y_categories=categories_high_corr)
```

### Distance
```{python}
if high_corr_idxes.any():
    plot_corr_with_dendro(resp_std_high_corr, kind=Correlation.DISTANCE_CORR, no_cbar=True, x_categories=categories_high_corr, y_categories=categories_high_corr)
```

### Partial
```{python}
if high_corr_idxes.any():
    plot_corr_with_dendro(resp_std_high_corr, kind=Correlation.PARTIAL, no_cbar=True, x_categories=categories_high_corr, y_categories=categories_high_corr)
```

### Partial (regularised)
```{python}
if high_corr_idxes.any():
    plot_corr_with_dendro(resp_std_high_corr, kind=Correlation.PARTIAL_GLASSO, no_cbar=True, x_categories=categories_high_corr, y_categories=categories_high_corr)
```

### VAR (Contemporaneous)
```{python}
if high_corr_idxes.any():
    plot_corr_with_dendro(resp_std_high_corr, kind=Correlation.VAR_CONTEMPORANEOUS, no_cbar=True, x_categories=categories_high_corr, y_categories=categories_high_corr)
```

### VAR (Temporal)
```{python}
if high_corr_idxes.any():
    plot_corr_with_dendro(resp_std_high_corr, kind=Correlation.VAR_TEMPORAL, no_cbar=True, x_categories=categories_high_corr, y_categories=categories_high_corr)
```

:::

## High partial (> 0.15)

```{python}
high_corr_cols, high_corr_idxes = filter_vars_by_abs_corr(resp_std, 0.15, kind=Correlation.PARTIAL)
resp_std_high_corr = resp.select(*ds_spec.SURVEY_COLS, *high_corr_cols)
categories_high_corr = ds_spec.CATEGORIES[high_corr_idxes]
```

::: {.panel-tabset}

### Pearson
```{python}
if high_corr_idxes.any():
    plot_corr_with_dendro(resp_std_high_corr, kind=Correlation.PEARSON, no_cbar=True, x_categories=categories_high_corr, y_categories=categories_high_corr)
```

### Distance
```{python}
if high_corr_idxes.any():
    plot_corr_with_dendro(resp_std_high_corr, kind=Correlation.DISTANCE_CORR, no_cbar=True, x_categories=categories_high_corr, y_categories=categories_high_corr)
```

### Partial
```{python}
if high_corr_idxes.any():
    plot_corr_with_dendro(resp_std_high_corr, kind=Correlation.PARTIAL, no_cbar=True, x_categories=categories_high_corr, y_categories=categories_high_corr)
```

### Partial (regularised)
```{python}
if high_corr_idxes.any():
    plot_corr_with_dendro(resp_std_high_corr, kind=Correlation.PARTIAL_GLASSO, no_cbar=True, x_categories=categories_high_corr, y_categories=categories_high_corr)
```

### VAR (Contemporaneous)
```{python}
if high_corr_idxes.any():
    plot_corr_with_dendro(resp_std_high_corr, kind=Correlation.VAR_CONTEMPORANEOUS, no_cbar=True, x_categories=categories_high_corr, y_categories=categories_high_corr)
```

### VAR (Temporal)
```{python}
if high_corr_idxes.any():
    plot_corr_with_dendro(resp_std_high_corr, kind=Correlation.VAR_TEMPORAL, no_cbar=True, x_categories=categories_high_corr, y_categories=categories_high_corr)
```

:::

## High contemporaneous (> 0.15)

```{python}
high_corr_cols, high_corr_idxes = filter_vars_by_abs_corr(resp_std, 0.15, kind=Correlation.VAR_CONTEMPORANEOUS)
resp_std_high_corr = resp.select(*ds_spec.SURVEY_COLS, *high_corr_cols)
categories_high_corr = ds_spec.CATEGORIES[high_corr_idxes]
```

::: {.panel-tabset}

### Pearson
```{python}
if high_corr_idxes.any():
    plot_corr_with_dendro(resp_std_high_corr, kind=Correlation.PEARSON, no_cbar=True, x_categories=categories_high_corr, y_categories=categories_high_corr)
```

### Distance
```{python}
if high_corr_idxes.any():
    plot_corr_with_dendro(resp_std_high_corr, kind=Correlation.DISTANCE_CORR, no_cbar=True, x_categories=categories_high_corr, y_categories=categories_high_corr)
```

### Partial
```{python}
if high_corr_idxes.any():
    plot_corr_with_dendro(resp_std_high_corr, kind=Correlation.PARTIAL, no_cbar=True, x_categories=categories_high_corr, y_categories=categories_high_corr)
```

### Partial (regularised)
```{python}
if high_corr_idxes.any():
    plot_corr_with_dendro(resp_std_high_corr, kind=Correlation.PARTIAL_GLASSO, no_cbar=True, x_categories=categories_high_corr, y_categories=categories_high_corr)
```

### VAR (Contemporaneous)
```{python}
if high_corr_idxes.any():
    plot_corr_with_dendro(resp_std_high_corr, kind=Correlation.VAR_CONTEMPORANEOUS, no_cbar=True, x_categories=categories_high_corr, y_categories=categories_high_corr)
```

### VAR (Temporal)
```{python}
if high_corr_idxes.any():
    plot_corr_with_dendro(resp_std_high_corr, kind=Correlation.VAR_TEMPORAL, no_cbar=True, x_categories=categories_high_corr, y_categories=categories_high_corr)
```

:::

## High temporal (> 0.1)

```{python}
high_corr_cols, high_corr_idxes = filter_vars_by_abs_corr(resp_std, 0.1, kind=Correlation.VAR_TEMPORAL)
resp_std_high_corr = resp.select(*ds_spec.SURVEY_COLS, *high_corr_cols)
categories_high_corr = ds_spec.CATEGORIES[high_corr_idxes]
```

::: {.panel-tabset}

### Pearson
```{python}
if high_corr_idxes.any():
    plot_corr_with_dendro(resp_std_high_corr, kind=Correlation.PEARSON, no_cbar=True, x_categories=categories_high_corr, y_categories=categories_high_corr)
```

### Distance
```{python}
if high_corr_idxes.any():
    plot_corr_with_dendro(resp_std_high_corr, kind=Correlation.DISTANCE_CORR, no_cbar=True, x_categories=categories_high_corr, y_categories=categories_high_corr)
```

### Partial
```{python}
if high_corr_idxes.any():
    plot_corr_with_dendro(resp_std_high_corr, kind=Correlation.PARTIAL, no_cbar=True, x_categories=categories_high_corr, y_categories=categories_high_corr)
```

### Partial (regularised)
```{python}
if high_corr_idxes.any():
    plot_corr_with_dendro(resp_std_high_corr, kind=Correlation.PARTIAL_GLASSO, no_cbar=True, x_categories=categories_high_corr, y_categories=categories_high_corr)
```

### VAR (Contemporaneous)
```{python}
if high_corr_idxes.any():
    plot_corr_with_dendro(resp_std_high_corr, kind=Correlation.VAR_CONTEMPORANEOUS, no_cbar=True, x_categories=categories_high_corr, y_categories=categories_high_corr)
```

### VAR (Temporal)
```{python}
if high_corr_idxes.any():
    plot_corr_with_dendro(resp_std_high_corr, kind=Correlation.VAR_TEMPORAL, no_cbar=True, x_categories=categories_high_corr, y_categories=categories_high_corr)
```

:::

-->

## Moderate--high correlation variables (Pearson $\geq 0.35$)

```{python}
plt.rc("figure", dpi=100)
```

```{python}
mod_corr_cols, med_corr_idxes  = filter_vars_by_abs_corr(resp_std, 0.35)
resp_std_mod_corr = resp.select(*ds_spec.SURVEY_COLS, *mod_corr_cols)
categories_med_corr = ds_spec.CATEGORIES[med_corr_idxes]
```

::: {.panel-tabset}

### Pearson
```{python}
plot_corr_with_dendro(resp_std_mod_corr, kind=Correlation.PEARSON, no_cbar=True, x_categories=categories_med_corr, y_categories=categories_med_corr)
```

### Partial
```{python}
plot_corr_with_dendro(resp_std_mod_corr, kind=Correlation.PARTIAL, no_cbar=True, x_categories=categories_med_corr, y_categories=categories_med_corr)
```

### Partial (regularised)
```{python}
plot_corr_with_dendro(resp_std_mod_corr, kind=Correlation.PARTIAL_GLASSO, no_cbar=True, x_categories=categories_med_corr, y_categories=categories_med_corr)
```

### VAR (Contemporaneous)
```{python}
plot_corr_with_dendro(resp_std_mod_corr, kind=Correlation.VAR_CONTEMPORANEOUS, no_cbar=True, x_categories=categories_med_corr, y_categories=categories_med_corr)
```

### VAR (Temporal)
```{python}
plot_corr_with_dendro(resp_std_mod_corr, kind=Correlation.VAR_TEMPORAL, no_cbar=True, x_categories=categories_med_corr, y_categories=categories_med_corr)
```

:::

# Low-correlation variables

<!--
We select those questions with maximum correlation less than some threshold (0.2 for Pearson correlation, 0.15 for partial correlation). Five questions feature in both sets:

- `pol_worry_econ`: Worry about the economy
- `cvcc10_cc`: Optimism that CC will be solved with technology
- `dem_urban`: Urban/Suburban/Rural
- `dem_income`: Income level
- `future`: In next 5y, quality of life for family expected to... get worse; get better.

The Pearson correlation analysis also highlights `cc11` (capacity to avoid CC-related death through own actions), `pol11` (political viewpoint: in times of crisis, the govt should take control vs. maintain civil liberties), and `pol11_pi` (second-order social belief for `pol11`).

The partial correlation analysis also highlights `cc1` (belief that climate change is happening), `cvcc_worryothers` (how worried are people, generally, about CC), and `pol10` (regarding the fairness of the American political system).
-->

## Pearson $\leq 0.25$
```{python}
low_corr_cols, low_corr_idxes = filter_vars_by_abs_corr(resp_std, upper=0.25, predicate="all")
categories_low_corr = ds_spec.CATEGORIES[low_corr_idxes]
```

::: {.panel-tabset}
### Pearson
```{python}
if low_corr_idxes.any():
    plot_corr_with_dendro(resp_std, kind=Correlation.PEARSON, y_vars=low_corr_cols, no_cbar=True, x_categories=ds_spec.CATEGORIES, y_categories=ds_spec.CATEGORIES)
```

### Partial
```{python}
if low_corr_idxes.any():
    plot_corr_with_dendro(resp_std, kind=Correlation.PARTIAL, y_vars=low_corr_cols, no_cbar=True, x_categories=ds_spec.CATEGORIES, y_categories=ds_spec.CATEGORIES)
```

### Partial (regularised)
```{python}
if low_corr_idxes.any():
    plot_corr_with_dendro(resp_std, kind=Correlation.PARTIAL_GLASSO, y_vars=low_corr_cols, no_cbar=True, x_categories=ds_spec.CATEGORIES, y_categories=ds_spec.CATEGORIES)
```

### VAR (Contemporaneous)
```{python}
if low_corr_idxes.any():
    plot_corr_with_dendro(resp_std, kind=Correlation.VAR_CONTEMPORANEOUS, y_vars=low_corr_cols, no_cbar=True, x_categories=ds_spec.CATEGORIES, y_categories=ds_spec.CATEGORIES)
```

### VAR (Temporal)
```{python}
if low_corr_idxes.any():
    plot_corr_with_dendro(resp_std, kind=Correlation.VAR_TEMPORAL, y_vars=low_corr_cols, no_cbar=True, x_categories=ds_spec.CATEGORIES, y_categories=ds_spec.CATEGORIES)
```
:::

## Partial $\leq 0.15$
```{python}
low_corr_cols, low_corr_idxes = filter_vars_by_abs_corr(resp_std, upper=0.15, predicate="all", kind=Correlation.PARTIAL)
categories_low_corr = ds_spec.CATEGORIES[low_corr_idxes]
```

::: {.panel-tabset}
### Pearson
```{python}
if low_corr_idxes.any():
    plot_corr_with_dendro(resp_std, kind=Correlation.PEARSON, y_vars=low_corr_cols, no_cbar=True, x_categories=ds_spec.CATEGORIES, y_categories=ds_spec.CATEGORIES)
```

### Partial
```{python}
if low_corr_idxes.any():
    plot_corr_with_dendro(resp_std, kind=Correlation.PARTIAL, y_vars=low_corr_cols, no_cbar=True, x_categories=ds_spec.CATEGORIES, y_categories=ds_spec.CATEGORIES)
```

### Partial (regularised)
```{python}
if low_corr_idxes.any():
    plot_corr_with_dendro(resp_std, kind=Correlation.PARTIAL_GLASSO, y_vars=low_corr_cols, no_cbar=True, x_categories=ds_spec.CATEGORIES, y_categories=ds_spec.CATEGORIES)
```

### VAR (Contemporaneous)
```{python}
if low_corr_idxes.any():
    plot_corr_with_dendro(resp_std, kind=Correlation.VAR_CONTEMPORANEOUS, y_vars=low_corr_cols, no_cbar=True, x_categories=ds_spec.CATEGORIES, y_categories=ds_spec.CATEGORIES)
```

### VAR (Temporal)
```{python}
if low_corr_idxes.any():
    plot_corr_with_dendro(resp_std, kind=Correlation.VAR_TEMPORAL, y_vars=low_corr_cols, no_cbar=True, x_categories=ds_spec.CATEGORIES, y_categories=ds_spec.CATEGORIES)
```
:::

# Hierarchical feature clustering

::: {.panel-tabset}

## Single linkage
```{python}
fig, ax = plt.subplots(figsize=(3,7), constrained_layout=True)
plot_feature_dendro(resp_std.drop(*ds_spec.SURVEY_COLS), method=LinkageMethod.SINGLE, ax=ax)
```

## Complete linkage
```{python}
fig, ax = plt.subplots(figsize=(3,7), constrained_layout=True)
plot_feature_dendro(resp_std.drop(*ds_spec.SURVEY_COLS), method=LinkageMethod.COMPLETE, ax=ax)
```

## Average linkage
```{python}
fig, ax = plt.subplots(figsize=(3,7), constrained_layout=True)
plot_feature_dendro(resp_std.drop(*ds_spec.SURVEY_COLS), method=LinkageMethod.AVERAGE, ax=ax)
```

:::


# EFA

## Parallel analysis: determining appropriate number of factors 

We calculate the eigenvalues of the true correlation matrix (blue), and those of a correlation matrix generated from random data (red). After/around the crossover point, additional factors are considered to reflect only noise. In this case we take $n=3$.

```{python}
plt.rc("figure", dpi=200)
```

```{python}
rng = np.random.default_rng(202602271618)

true_eigs = pa_true_eigs(resp_std)
rand_eigs = pa_random_eigs(resp_std, repeats=100, rng=rng)

fig, ax = plt.subplots(figsize=(4.5,2), constrained_layout=True)
ax.plot(np.arange(len(true_eigs)), true_eigs, color="tab:blue", label="Data")
ax.plot(np.arange(len(rand_eigs)), rand_eigs, color="tab:red", label="Random")
ax.set_xticks(np.arange(0, len(true_eigs), 2), np.arange(0, len(true_eigs), 2) + 1)

ax.set_xlim(0, 44)
ax.set_ylim(0, None)
ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)
ax.set_xlabel("Eigenvalue sorted index (decreasing)")
ax.set_ylabel("Eigenvalue")
ax.legend();
```

## Factor analysis / PCA results ($n=3$)

```{python}
plt.rc("figure", dpi=100)
```

```{python}
cmap = sns.diverging_palette(20, 230, as_cmap=True)

n_factor = 3
labels = np.asarray(resp_std.drop(*ds_spec.SURVEY_COLS).columns)

X = resp_std.drop(*ds_spec.SURVEY_COLS).to_numpy()

efa = Factor(
    X,
    n_factor=n_factor
).fit()

pca = PCA(n_components=n_factor)
pca.fit(X)
```

```{python}
all_categories = ["Belief", "Experience", "Attitude", "Behaviour", "Demographic", "External factor"]
category_pal = sns.husl_palette(len(all_categories), s=0.45)
category_lut = dict(
    zip(map(str, all_categories), category_pal)
)

category_colours = [category_lut[c] for c in ds_spec.CATEGORIES]
```

::: {.panel-tabset}

### EFA
```{python}
figsize = (0.25 * efa.loadings.shape[0] + 0.5, 0.2 * n_factor + 1.5)

g = sns.clustermap(
    efa.loadings.T,
    center=0,
    cmap=cmap,
    col_colors=category_colours,
    vmin=-1,
    vmax=1,
    method="ward",
    dendrogram_ratio=(0, 0.5),
    cbar_pos=None,
    linewidths=0.75,
    figsize=figsize,
    fmt=".1f",
    annot=True,
)

ord_labels = labels[g.dendrogram_col.reordered_ind]

g.ax_heatmap.set_xticks(np.arange(efa.loadings.shape[0]) + 0.5, ord_labels, rotation=45, horizontalalignment="right");
```

### PCA
```{python}
g = sns.clustermap(
    (pca.components_.T * np.sqrt(pca.explained_variance_)).T,
    center=0,
    cmap=cmap,
    vmin=-1,
    vmax=1,
    method="ward",
    col_colors=category_colours,
    dendrogram_ratio=(0, 0.5),
    cbar_pos=None,
    linewidths=0.75,
    figsize=figsize,
    fmt=".1f",
    annot=True,
)

ord_labels = labels[g.dendrogram_col.reordered_ind]

g.ax_heatmap.set_xticks(np.arange(pca.components_.shape[1]) + 0.5, ord_labels, rotation=45, horizontalalignment="right");
```
:::
