name: Publish static site

on:
  push: 
    branches:
      - main
      - 'ci/**'
  workflow_dispatch:

permissions:  {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
      with:
        submodules: false

    - name: Setup SSH for submodules
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SUBMODULE_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Init and update submodules
      run: |
        git submodule sync
        git submodule update --init --recursive

    - name: Install Typst
      uses: typst-community/setup-typst@v4
      with:
        typst-version: 0.14.0

    - name: Install uv
      uses: astral-sh/setup-uv@v7

    - name: Build site
      run: make site/site/index.html
      env:
        TYPST_PACKAGE_PATH: ${{ github.workspace }}/typst-packages

    - name: Upload site artefacts
      id: deployment
      uses: actions/upload-pages-artifact@v4
      with:
        path: site/site

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
