name: Publish static site

on:
  push: 
    branches:
      - main
      - 'ci/**'
  workflow_dispatch:

permissions:  {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
      with:
        persist-credentials: false
        #submodules: recursive

    - name: Checkout submodule
      run: |
        git submodule sync --recursive
        git -c protocol.version=2 submodule update --init --force --depth=1 --recursive

    - name: Install Typst
      uses: typst-community/setup-typst@v4
      with:
        typst-version: 0.14.0

    - name: Install uv
      uses: astral-sh/setup-uv@v7

    - name: Build site
      run: make site/site/index.html
      env:
        TYPST_PACKAGE_PATH: ${{ github.workspace }}/typst-packages

    - name: Upload site artefacts
      id: deployment
      uses: actions/upload-pages-artifact@v4
      with:
        path: site/site

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
